#!/usr/bin/env python3
"""Recompute the archived campaign without changing any observations.

The two-sided Student t interval uses df=99 and t(0.975)=1.9842169515086827.
It describes this single-board campaign under the usual independent-sample
assumption, not between-board uncertainty or a latency prediction interval.
"""
import argparse
import csv
import hashlib
import json
import math
from pathlib import Path
import re
import statistics

ROOT = Path(__file__).resolve().parents[1]


def analyze():
    evidence = ROOT / 'docs/evidence'
    csv_path = evidence / 'hybrid_handshake_100_runs.csv'
    log_path = evidence / 'hybrid_handshake_100_runs_raw.log'
    rows = list(csv.DictReader(csv_path.open(encoding='utf-8')))
    raw = log_path.read_text(encoding='utf-8').split('=== CAMPAIGN STATISTICAL SUMMARY')[0]
    logged = [line.split(',') for line in re.findall(r'CSV_DATA,([^\r\n]+)', raw)]
    if len(rows) != 100 or len(logged) != 100:
        raise ValueError('Expected exactly 100 archived observations')
    for index, (row, record) in enumerate(zip(rows, logged), 1):
        if list(row.values())[1:] != record[1:] or int(row['run']) != index:
            raise ValueError(f'CSV/log mismatch at ordinal {index}')
    if raw.count('Server response HMAC verification successful!') != 100:
        raise ValueError('Expected 100 HMAC success records')
    if raw.count('Session key derived via HKDF') != 100:
        raise ValueError('Expected 100 key derivations')
    failures = [line for line in raw.splitlines()
                if re.search(r'failed|local-only benchmark|retrying', line, re.I)]
    if failures:
        raise ValueError('Archived campaign contains failure/retry records')
    result = {
        'n': 100,
        'observed_completed_handshakes': 100,
        'observed_handshake_failures': 0,
        'watchdog_reset_api_errors': raw.count('task not found'),
        'raw_run_identifiers': sorted(set(row[0] for row in logged)),
        'run_identifier_note': 'CSV run is acquisition order 1..100; original firmware logged 0 for every row.',
        'timing_definition': 'total_ms = keygen_ms + handshake_ms; excludes intervening packing, logging and heap sampling.',
        'cycle_definition': 'Elapsed CCOUNT interval spans a broader instrumented region including waits/logging; not isolated CPU work.',
        'heap_definition': 'Three snapshots of free heap; not transient peak allocation; bytes, not KB.',
        'ci_method': 'Student t, two-sided 95%, df=99, sample SD (ddof=1), no outlier removal.',
        'sources': {str(p.relative_to(ROOT)).replace('\\', '/'): hashlib.sha256(p.read_bytes()).hexdigest()
                    for p in (csv_path, log_path)},
    }
    for field in ('total_ms', 'total_cycles', 'keygen_ms', 'handshake_ms', 'peak_heap_bytes'):
        values = [float(row[field]) for row in rows]
        mean = statistics.mean(values)
        sd = statistics.stdev(values)
        half = 1.9842169515086827 * sd / math.sqrt(len(values))
        result[field] = {'mean': mean, 'sample_sd': sd, 'ci95_mean': [mean-half, mean+half],
                         'min': min(values), 'max': max(values), 'median': statistics.median(values)}
    result['payload_bytes'] = sorted(set(int(row['payload_bytes']) for row in rows))
    result['latency_runs_over_1000_ms'] = sum(float(row['total_ms']) > 1000 for row in rows)
    return result


def tex_values(result):
    latency = result['total_ms']
    cycles = result['total_cycles']
    items = {
        'BenchmarkMeanMs': latency['mean'], 'BenchmarkSdMs': latency['sample_sd'],
        'BenchmarkLowMs': latency['ci95_mean'][0], 'BenchmarkHighMs': latency['ci95_mean'][1],
        'BenchmarkMinMs': latency['min'], 'BenchmarkMaxMs': latency['max'],
        'BenchmarkCyclesM': cycles['mean']/1e6, 'BenchmarkCyclesSdM': cycles['sample_sd']/1e6,
        'BenchmarkCyclesLowM': cycles['ci95_mean'][0]/1e6,
        'BenchmarkCyclesHighM': cycles['ci95_mean'][1]/1e6,
        'BenchmarkCyclesMinM': cycles['min']/1e6, 'BenchmarkCyclesMaxM': cycles['max']/1e6,
    }
    return '% Generated by tools/analyze_submission.py; do not hand-edit.\n' + ''.join(
        '\\newcommand{\\' + name + '}{' + f'{value:.2f}' + '}\n' for name, value in items.items())


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Validate tracked analysis outputs without writing')
    args = parser.parse_args()
    result = analyze()
    outputs = {
        ROOT/'docs/evidence/campaign_reanalysis.json': json.dumps(result, indent=2) + '\n',
        ROOT/'docs/benchmark_values.tex': tex_values(result),
    }
    for path, content in outputs.items():
        if args.check:
            if path.read_text(encoding='utf-8') != content:
                raise ValueError(f'Stale analysis output: {path}')
        else:
            path.write_text(content, encoding='utf-8', newline='\n')
    print('PASS: 100 numerical CSV/log records, HMAC results and derived statistics agree.')
    print(json.dumps({key: result[key] for key in ('total_ms', 'total_cycles', 'peak_heap_bytes')}, indent=2))


if __name__ == '__main__':
    main()
